[package]
name = "moviegram"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
chrono = "0.4.38"
log = "0.4.22"
pretty_env_logger = "0.5.0"
reqwest = "0.12.9"
soup = "0.5.1"
tokio = { version = "1.41.0", features = ["full"] }
